### ISSUE TITLE
Realms - BN.js more UI errors when calling .toNumber()

### ISSUE THREAD

**Issue by shupcode** [helium/helium-program-library#210]
Details left on comments at previously closed issue 206:

https://github.com/helium/helium-program-library/issues/206

**Comment by bryzettler** [comment]
@shupcode thanks for doing the spelunking, I imitated a position of your size and fixed any additional BN issues. Should be deployed at [realms.heliumvote.com](http://realms.heliumvote.com/dao/hnt) and [app.realms.today](http://app.realms.today/dao/hnt) once the upstream [pr](https://github.com/solana-labs/governance-ui/pull/1584) is merged.

Let me know if its good on your end and we can close this issue
