### ISSUE TITLE
Helium program library packages do not work with webpack

### ISSUE THREAD

**Issue by ChewingGlass** [helium/helium-program-library#237]
https://github.com/BenoitDuffez/hpl-webpack

This repo reproduces

**Comment by BenoitDuffez** [comment]
This is a minor issue. I wanted to use `sendAndConfirmWithRetry` to onboard, but since webpack isn't happy, I'm using `sendAndConfirmRawTransaction` from solana web3.

I'd rather use your code, but using the lower level web3 client works fine.

**Comment by ChewingGlass** [comment]
@BenoitDuffez Our docs repo is webpack. Can you try following its configs https://github.com/helium/docs/blob/master/docusaurus.config.js#L145

**Comment by BenoitDuffez** [comment]
@ChewingGlass does it use this repo? I don't see it in `package.json`. I'll try with this config though, thanks.

**Comment by BenoitDuffez** [comment]
Sorry for the delay. This is what solved it

```
new webpack.ProvidePlugin({
  process: require.resolve('process/browser'),
})
```

Thanks! (I can't close this ticket apparently)
