### ISSUE TITLE
Add Nebra 5G maker key

### ISSUE THREAD

**Issue by Sophi** [helium/helium-program-library#241]
maker: Nebra 5G
pubkey: 13aBYzpWA6ELqB4L2bQeXd2FH2QMRUMHZAioQawLbSZEqaDVXeh
mode: full

**Comment by ChewingGlass** [comment]
Done: https://explorer.solana.com/tx/24n1mjDb8KSAenNi7HdwSY62AwJYjadvTUfg13pnF3JqBCpFTQ2MFpY2UQKug2HXb3P19fC3AEy7W2DEtojBqvvt?cluster=
