### ISSUE TITLE
 migration, it seems not successful.

### ISSUE THREAD

**Issue by bertonhe** [helium/helium-program-library#268]
migration, it seems not successful.  here is the following: 
% env MIGRATION_SERVICE_URL=https://migration.web.helium.io env SOLANA_URL=https:/api.mainnet-beta.solana.com env SOLANA_WSS_URL=wss://api.mainnet-beta.solana.com ./migration-tx-executor --wallet solana_wallet.json
Migrating wallet solana_wallet.json
https://migration.web.helium.io/migrate/solana_wallet.json?limit=1000&offset=0
https://migration.web.helium.io/migrate/solana_wallet.json?limit=1000&offset=1000
% spl-token accounts -v
Program                                       Token                                         Account                                       Delegated  Close Authority  Balance
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

If I migration it using app, the following is a different result.
% spl-token accounts -v
Program                                       Token                                         Account                                       Delegated  Close Authority  Balance
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA   hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux

**Comment by bertonhe** [comment]
![Uploading image.png…]()

**Comment by bertonhe** [comment]
![image](https://github.com/helium/helium-program-library/assets/3388995/e8d773b8-d678-4ada-a4b0-9984121b9366)

**Comment by ChewingGlass** [comment]
You need to specify the wallet as a public key, not as a json file.
